/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService */

#ifndef _Included_org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService
#define _Included_org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService
#ifdef __cplusplus
extern "C" {
#endif
#undef org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService_METRIC_L2
#define org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService_METRIC_L2 0L
#undef org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService_METRIC_INNER_PRODUCT
#define org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService_METRIC_INNER_PRODUCT 1L
/*
 * Class:     org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService
 * Method:    kmeansWithDistances
 * Signature: (JIIIII)Lorg/opensearch/knn/memoryoptsearch/faiss/reorder/kmeansreorder/KMeansResult;
 */
JNIEXPORT jobject JNICALL Java_org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService_kmeansWithDistances
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService
 * Method:    kmeansWithDistancesMMap
 * Signature: (JIIIII)Lorg/opensearch/knn/memoryoptsearch/faiss/reorder/kmeansreorder/KMeansResult;
 */
JNIEXPORT jobject JNICALL Java_org_opensearch_knn_memoryoptsearch_faiss_reorder_kmeansreorder_FaissKMeansService_kmeansWithDistancesMMap
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
